---
- name: Create "{{dest}}" directory.
  file: path={{dest}} state=directory

- name: Clone "{{repo}}".
  git: repo={{repo}} dest={{dest}} version=14eee6bf7e69593149445bea8dc1744adb647fcf force=yes
