---
galaxy_info:
  author: Nik Kinkel
  description: Install and configure golang.
  license: BSD
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - squeeze
        - wheezy
  categories:
    - development
    - packaging
dependencies: []
