[MasterConfig]
Logfile = "/var/log/projectmain/core.log"

#[[LoggerConfig]]
#Name = "logger"
#Path = "/usr/local/bin/filelogger"

[[LoggerConfig]]
Name = "Splunk"
Path = "/usr/local/bin/Splunk"
Args = ["-config","/etc/projectmain/Splunk-config.toml"]

[[PluginConfig]]
Name = "webauth"
Path = "/usr/local/bin/webauth"
Args = ["-config","/etc/projectmain/webauth-config.toml"]

[[PluginConfig]]
Name = "fssh"
Path = "/usr/local/bin/fssh"
Args = ["-config","/etc/projectmain/fssh-config.toml"]

[[PluginConfig]]
Name = "dnp3"
Path = "/usr/local/bin/dnp3"
Args = ["-config","/etc/projectmain/dnp3-config.toml"]

