[[Endpoint]]
Host = "192.168.42.43"
Port = 8088
URL = "/services/collector"
AuthToken = "CF141FE6-85B1-4BE6-B2DE-1FB9FA01793A"
RootCAs = ["/home/deploy/src/github.com/Senior-Design-May1601/Splunk/cacert.pem"]

