[[Endpoint]]
Host = "192.168.42.43"
Port = 8088
URL = "/services/collector"
AuthToken = "8DCA8AF2-ACD9-43C6-9C46-458C78641EEA"
RootCAs = ["/home/deploy/src/github.com/Senior-Design-May1601/Splunk/cacert.pem"]

