---

- name: reboot {{host}}
  command: shutdown -r now "ansible reboot initiated" 
  async: 0
  poll: 0
  ignore_errors: true
 
- name: Waiting for {{host}} to reboot
  local_action: wait_for host={{ host }} state=started delay=60 connect_timeout=10 port=22
  sudo: false
