---
##for documentation on configuring splunk http-eventcollector via CLI visit
##http://dev.splunk.com/view/event-collector/SP-CAAAE7D

- name: Create Directory
  file: path=/opt/splunk state=directory

- name: Download Splunk
  shell: wget http://download.splunk.com/products/splunk/releases/6.3.3/linux/splunk-6.3.3-f44afce176d0-linux-2.6-intel.deb; cp splunk-6.3.3-f44afce176d0-linux-2.6-intel.deb /opt/splunk
  args:
    creates: splunk-6.3.3-f44afce176d0-linux-2.6-intel.deb

- name: Install Splunk
  shell: dpkg -i splunk-6.3.3-f44afce176d0-linux-2.6-intel.deb
    creates=/opt/splunk/bin/splunk

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start --accept-license

#- name: Config Bash
#  shell: export SPLUNK_HOME/opt/splunk
#; export PATH=$SPLUNK_HOME/bin:$PATH; 
- name: Config Splunk
  shell: /opt/splunk/bin/splunk http-event-collector create Honeypot-Event -uri https://localhost:8089 -disabled 0 -index log -auth admin:changeme 
    creates=/opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
