---
- name: Create Directory
  file: path=/opt/splunk state=directory

- name: Download Splunk
  get_url: url=http://download.splunk.com/products/splunk/releases/6.3.2/splunk/linux/splunk-6.3.2-aaff59bb082c-linux-2.6-intel.deb dest=/opt/splunk/splunk-6.3.2-aaff59bb082c-linux-2.6-intel.deb force=no

- name: Install Splunk
  shell: dpkg -i /opt/splunk/splunk-6.3.2-aaff59bb082c-linux-2.6-intel.deb
    creates=/opt/splunk/bin/splunk

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start --accept-license

#- name: Config Bash
#  shell: export SPLUNK_HOME/opt/splunk
#; export PATH=$SPLUNK_HOME/bin:$PATH; 
- name: Config Splunk
  shell: /opt/splunk/bin/splunk http-event-collector create my-test-token -uri https://localhost:8088 -disabled 0 -index log -auth admin:changeme 
    creates=/opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
