---
galaxy_info:
  author: Dan Borgerding
  description: general config role for config.toml files in go directories.
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - development
dependencies: []
