---
galaxy_info:
  author: Nik Kinkel
  description: Lockdown SSH.
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - networking
  - system
dependencies: []
