---
- name: Configure {{name}} service.
  template: src=service.j2 dest="/etc/systemd/system/{{name}}.service" owner=root group=root mode=0644

- name: Enable {{name}} service at boot.
  service: name={{name}} enabled=yes

- name: Start {{name}} service.
  service: name={{name}} state=started
