---
- name: check if {{name}} already exists
  stat: path="/etc/systemd/system/{{name}}"

- name: Configure {{name}}.
  template: src=service.j2 force=no dest="/etc/systemd/system/{{name}}" owner=root group=root mode=0644

- name: Enable {{name}} at boot.
  service: name={{name}} enabled=yes

- name: Start {{name}}.
  service: name={{name}} state=started
