---
- name: Build {{package}} package.
  shell: . /etc/profile; go build
  args:
    chdir: "{{Src_Dir}}/{{package}}"

#- name: Move {{package}} to {{Work_Dir}}.
#  command: mv {{Src_Dir}}/{{package}} {{Work_Dir}}
