---
- name: Create {{bin_dir}} directory.
  file: path={{bin_dir}} state=directory

- name: Build {{package}} package.
  command: go build
  args:
    chdir: "{{src_dir}}"

- name: Move {{package}} to {{bin_dir}}.
  command: mv {{src_dir}}/webauth {{bin_dir}}
