---
##installs dated version of goLang, opt to install from source
#- name: Install golang.
#  apt: name=golang state=present


#- name: Download Go Tarball.
#  get_url: url=https://storage.googleapis.com/golang/go1.5.3.linux-386.tar.gz dest=/usr/local/src/go1.5.3.linux-386.tar.gz

- name: Install Golang from source.
  unarchive: src=https://storage.googleapis.com/golang/go1.5.3.linux-386.tar.gz dest=/usr/local/bin/ creates=/usr/local/bin/go/README.md copy=no #group=deploy mode=0644

# standard: $ export PATH=$PATH:/usr/local/go/bin will not work
#- name: set GOPATH.
#  lineinfile: dest=/etc/profile state=present line='PATH=$PATH:/usr/local/go/bin

