---
##installs dated version of goLang, opt to install from source
#- name: Install golang.
#  apt: name=golang state=present

- name: Download Go Tarball.
  get_url: url="{{Go_Source}}" dest="/usr/local/src/{{Go_Source_File}}"

- name: unpack tarball
  unarchive: src="/usr/local/src/{{Go_Source_File}}" dest=/usr/local/ copy=no

- name: Go arm dependencies Mercurial
  apt: name=mercurial state=present

- name: Go arm dependencies gcc
  apt: name=gcc state=present

- name: Go arm dependencies libc6-dev
  apt: name=libc6-dev state=present

  #standard: $ export PATH=$PATH:/usr/local/go/bin will not work
- name: set GO path.
  lineinfile: "dest=/etc/profile state=present line='export PATH=$PATH:/usr/local/go/bin'"

- name: set GOPATH.
  lineinfile: "dest=/etc/profile state=present line='export GOPATH=$HOME'"
