---
- name: Hash deploy password in crypt format
  command: mkpasswd --method=SHA-512 {{deploy_pass}}
  register: dp_hashed

- name: Setup deploy user
  user: name=deploy password="{{dp_hashed.stdout}}" groups=sudo append=yes shell=/bin/bash

- name: Setup public key auth for deploy account
  authorized_key: user=deploy
                  key="{{lookup('file', item)}}"
  with_items: deploy_key
