---
- name: Set deploy password fact
  set_fact:
    deploy_passwd: "{{lookup('csvfile', 'deploy file=../../../secret/passwords/deploy.csv delimiter=,')}}"

- name: Hash deploy password in crypt format
  command: mkpasswd --method=SHA-512 {{deploy_passwd}}
  register: dp_hashed

- name: Setup deploy user
  user: name=deploy password="{{dp_hashed.stdout}}" groups=sudo append=yes

- name: Setup public key auth for deploy account
  authorized_key: user=deploy
                  key="{{lookup('file', item)}}"
  with_items: deploy_key
