---
- name: Disable root login over SSH
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present 
  notify: restart ssh

- name: Disable SSH password login
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- name: Set SSH Authentication Methods
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^AuthenticationMethods" line="AuthenticationMethods publickey" state=present
  notify: restart ssh

- name: Set SSH privilege sep
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^UsePrivilegeSeparation" line="UsePrivilegeSeparation sandbox" state=present
  notify: restart ssh

- name: Disable X11 Forwarding
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^X11Forwarding" line="X11Forwarding no" state=present
  notify: restart ssh

- name: Only allow deploy SSH user
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^AllowUsers" line="AllowUsers deploy" state=present
  notify: restart ssh

- name: Set modern SSH ciphers
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^Ciphers" line="Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr" state=present
  notify: restart ssh

- name: Set modern SSH MACs
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^MACs" line="MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com" state=present
  notify: restart ssh

# TODO: change SSH port
