---
- name: Install iptables-persistent
  apt: pkg=iptables-persistent state=present

- name: Copy iptables rules
  copy: src=../files/rules.v4 dest=/etc/iptables/rules.v4 owner=root group=root mode=0644

- name: reload iptables
  shell: iptables-restore < /etc/iptables/rules.v4

- name: DEBUG
  shell: echo iptables-restore has run
