---
galaxy_info:
  author: Nik Kinkel
  description: Install git.
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - development
  - system
dependencies: []
