---
- name: Hash root password in crypt format
  command: mkpasswd --method=SHA-512 {{root_pass}}
  register: rp_hashed

- name: Change root password
  user: name=root password="{{rp_hashed.stdout}}"
