---
galaxy_info:
  author: Dan Borgerding
  description: provision debian 7-32 Vm with Splunk http-event-collector
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - development
dependencies: []
