---
## playbook to setup default raspberry pi

-
    name: User Config
    hosts: pi
    vars_files:
        - vars/secrets.yml
    sudo: yes

    roles:
      - {role: create-pi-user, sudo: yes}
...
