---
## playbook to setup default raspberry pi

-
    name: User Config
    hosts: pi
    vars_files:
        - vars/secrets.yml
    vars:
        deploy_key: keys/deploy-key.pub 

    roles:
      - {role: init-pi, become: yes}
      - {role: reboot, become: yes, host: 192.168.42.42, when: ansible_service_mgr=="sysvinit"}

...
