# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.provider "virtualbox" do |v|
  		v.gui = true
	end
	config.vm.define "splunk" do |splunk|
                splunk.vm.box = "puppetlabs/debian-7.8-32-puppet"
                #set private static network address
                splunk.vm.network :private_network, ip:'192.168.42.43'
                #port forward splunk web interface to host machine
                #can access interface at http://192.168.42.43:8000
                splunk.vm.network "forwarded_port", guest:8000,host:8000
                #provision splunk server
                splunk.vm.provision "ansible" do |ansible|
                        ansible.playbook = "splunk-server-setup.yml"
                	ansible.verbose = true
		end
        end

	config.vm.define "pi" do |pi|
		pi.vm.box = "puppetlabs/debian-7.8-32-puppet"		
		
		#set private static network address
		pi.vm.network :private_network, ip:'192.168.42.42'
		#pi.vm.network "forwarded_port", guest:22,host:22 
		#disable synced folders for pi machine
		#:pi.vm.synced_folder ".", "/vagrant", disabled:true

		#build default Raspberry Pi environment	
		pi.vm.provision "ansible" do |ansible|
			ansible.ask_vault_pass = false
			ansible.playbook = "pi-start.yml"
		end					
		#provision Pi as Honeypot device
		pi.vm.provision "ansible" do |ansible|
			ansible.playbook = "bootstrap-playbook.yml"
			ansible.force_remote_user = false
			ansible.verbose = true
		#force paramiko connection mode
		#	ansible.raw_arguments = ["--connection=paramiko"]
		end
 	end
end

