---
- name: Install whois
  apt: name=whois state=present update_cache=yes

- name: Install git
  apt: name=git state=present

- name: Install libcap2-bin
  apt: name=libcap2-bin state=present

- name: Install apticron
  apt: name=apticron state=present

- name: Set admin security email updates
  lineinfile: dest=/etc/apticron/apticron.conf state=present regexp="EMAIL=" line="EMAIL=\"{{admin_email}}\""

- name: Set email host name
  lineinfile: dest=/etc/apticron/apticron.conf state=present regexp="SYSTEM=" line="SYSTEM=\"Raspbery Pi Honeypot\""
