---
galaxy_info:
  author: Dan Borgerding
  description: Set up a default Raspberry Pi
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - system
dependencies: []
