---

- name: Set user pi pass
  command: mkpasswd --method=SHA-512 {{default_pi_pass}}
  register: pi_pass_hashed
  
- name: Create Pi user
  user: name=pi password="{{pi_pass_hashed.stdout}}" groups=sudo append=yes

#- name: Enable persistant vagrant access
#  action: lineinfile dest=/etc/ssh/sshd_config regexp="^AllowUsers" line="AllowUsers vagrant" state=present

- name: Install SystemD
  apt: name=systemd state=present

- name: Install Systemd-sysv
  shell: echo "Yes, do as I say!" | apt-get install -y -q --force-yes systemd-sysv

- name: reboot pi
  command: shutdown -r now "ansible reboot initiated" 
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot is undefined

- name: Waiting for host to reboot
  local_action: wait_for host=192.168.42.42 state=started delay=60 connect_timeout=10 port=22
  sudo: false
  when: reboot is undefined

- name: Prevent future ansible reboots
  set_fact: reboot="false"

