---

- name: Set user pi pass
  command: mkpasswd --method=SHA-512 {{default_pi_pass}}
  register: pi_pass_hashed
  
- name: Create Pi user
  user: name=pi password="{{pi_pass_hashed.stdout}}" groups=sudo append=yes

#- name: Enable persistant vagrant access
#  action: lineinfile dest=/etc/ssh/sshd_config regexp="^AllowUsers" line="AllowUsers all" state=present

- name: Install SystemD
  apt: name=systemd state=present

- name: Install Systemd-sysv
  shell: echo "Yes, do as I say!" | apt-get install -y -q --force-yes systemd-sysv   

- name: Setup public key auth for Pi account(testing only)
  authorized_key: user=pi
                  key="{{lookup('file', item)}}"
  with_items: deploy_key

