---
galaxy_info:
  author: Nik Kinkel
  description: Create a directory and clone a git repo.
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - development
dependencies: []
