---
galaxy_info:
  author: Nik Kinkel
  description: Create an unprivileged system user.
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
    - squeeze
    - wheezy
  categories:
  - system
dependencies: []
